services:
  mongo-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
  myapp:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo-db
    environment:
      MONGO_DB_URL: mongodb://mongo-db:27017/mydatabase
